# Site settings
title: Can They See My Dick?
description: > # this means to ignore newlines until "baseurl:"
  Can the US government see your dick pics?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cantheyseemydick.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
